[build]
  command = "rm -rf .next && ls -la components/ui && npm ci && npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--force"

[[plugins]]
  package = "@netlify/plugin-nextjs"
